### ISSUE TITLE
Document power fault flag meanings

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#102]
UNDER_VOLTAGE_FLAG
    OVER_VOLTAGE_FLAG
    OVER_CURRENT_FLAG
    MEASUREMENT_ERROR_FLAG
    SHUNT_OVERLOAD_FLAG

Also document LCD screen pages.

**Comment by DougCoffland** [comment]
I put the meanings of the flags in the manual as I understood them.
