### ISSUE TITLE
Error when homing

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#107]
When I click the home button on the dyna, I get an error that says this.

Level | Source | Location | Repeat | Message
-- | -- | -- | -- | --
error | tornado.access | web.py:2063 | 1 | 500 PUT /api/home/x (10.0.0.24) 10.07ms
error | tornado.application | web.py:1590 | 1 | Uncaught exception PUT /api/home/x (10.0.0.24) HTTPServerRequest(protocol='http', host='10.0.0.21', method='PUT',  uri='/api/home/x', version='HTTP/1.1', remote_ip='10.0.0.24',  headers={'Host': '10.0.0.21', 'Content-Length': '0', 'Referer':  'http://10.0.0.21/', 'Accept-Encoding': 'gzip, deflate', 'Accept':  'application/json, text/javascript, */*; q=0.01', 'Accept-Language':  'en-US,en;q=0.5', 'X-Requested-With': 'XMLHttpRequest', 'User-Agent':  'Mozilla/5.0 (X11; Linux i686; rv:52.0) Gecko/20100101 Firefox/52.0',  'Connection': 'keep-alive'})

**Comment by jcoffland** [comment]
I've fixed these ugly error dumps in v0.3.10.
