### ISSUE TITLE
Position not set after homing

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#109]
When homing the Z axis on the Dyna, the position is set to the max-soft-limit value specified in the motor configuration. I would expect the X and Y axes to be somewhat the same and set the Position to the min-soft-limit value after homing. This doesn't happen. The value seems to just stay at the value it was after the homing movements are complete.

**Comment by jcoffland** [comment]
This appears to be working correctly in v0.3.10.
