### ISSUE TITLE
Contoller booting...Please Wait no longer displays when booting

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#121]
After loading 0.3.13 on two different boxes, I noticed that the boot up message "Controller booting...Please wait" no longer displays. Now I get a screen that looks like the LCD screen is out of adjustment during that period. By this, I mean that their are two rows of character that show darker than the rest of the screen but there are not characters present.

When the system boots, the normal display comes up, but the axis positions don't display until the axis is first moved. I am opening another issue on that.

**Comment by jcoffland** [comment]
Fixed in v0.3.14.
