### ISSUE TITLE
Add ability to download GCode from controller

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#125]

**Comment by DougCoffland** [comment]
Now that we are offering control from a local monitor, keyboard, and mouse, this capability is critical. At present, users will set up their system without a network and find that they don't have any way to load a G-code program. They have to be able to read their programs from a USB drive if they want to do local operation. The only other way is to access the controller from a computer across a network and download the program from there. This pretty much defeats the purpose of local operation altogether.

**Comment by jcoffland** [comment]
What you are asking for is already possible.  Just insert a USB drive and you can access the files on it.  This issue is about being able to download files already loaded on the controller from the Web.

**Comment by DougCoffland** [comment]
I am not able to see the USB drive in the file finder dialog.

**Comment by DougCoffland** [comment]
I misunderstood the meaning of this issue, so I opened issue #149 to document the USB access issue.

**Comment by jcoffland** [comment]
Added in 0.4.3-rc2
