### ISSUE TITLE
Stopping affects following commands.

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#127]
If I click the play button and then select stop from the tool change dialog, I can no longer zero an axis.

This came up when I started a program but then remembered that I had not zeroed an axis while the tool change dialog was there. I selected stop, but could not set the axis to zero. I had to reboot to regain the ability to set the axis to zero.

**Comment by jcoffland** [comment]
Fixed in v0.3.19.
