### ISSUE TITLE
Homing broken

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#140]
Homing stopped working after loading 0.3.24 beta. If fails in the following situation:
* min-switch is set to normally open
* homing-mode is set to switch-min
Then go to the Control screen and click the home button for that axis. The state changes to 'HOMING', but the axis does not move. The only way that I have found to get out of this state is to change the homing-mode to manual. Rebooting the browser and rebooting the controller do not help.

**Comment by jcoffland** [comment]
Do you have your soft limits set?

**Comment by DougCoffland** [comment]
Yes, the soft limits are set. This configuration homes correctly in 0.3.20 and fails in 0.3.24 beta.

**Comment by jcoffland** [comment]
I figured out what was wrong.

**Comment by makerstorage** [comment]
Same is here
