### ISSUE TITLE
Huanyang VFD disconnected after clicking stop

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#141]
Clicking the stop button in the middle of the G-Code program leaves the Huanyang spindle "Disconnected". When you restart the program, the program starts, but the spindle does not turn on. The 'Messages' tab shows 'Disconnected'.

I have only found two ways to get the spindle to reconnect. One is to reboot the controller. The other is to change the 'tool-type' to 'Disabled" on the tool page, save the change, and then change it back Huangyang.

This testing was done on 0.3.24 beta. I have not tried it on earlier versions.

**Comment by jcoffland** [comment]
I believe this is now fixed.  Try out beta 0.3.24 again.

**Comment by DougCoffland** [comment]
resolved
