### ISSUE TITLE
Controller display should follow G20 and G21 commands

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#146]
Nice job on the Imperial units support. It might be an improvement to have the controller display change to match the program that is currently being executed. For instance, the display would display in imperial units when a G20 is encountered and in metric when a G21 is encountered.

**Comment by jcoffland** [comment]
Fixed in the latest v0.3.25 beta.  Both the LCD and control view show values in the current machine units.  The new SETTINGS tab lets you set ``units`` which sets both the units used in motor configuration and the default machine units.

**Comment by DougCoffland** [comment]
This looks good.
