### ISSUE TITLE
'VFD Test' is confusing

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#151]
The 'VFD Test' selection on the pull-down menu on the 'TOOL'  page is confusing. it seems that the Modbus Test table is the only part that is actually used and that table seems to be active even though the 'Save' button has not been clicked. In addition, it does not have any affect on the Huanyang VFD. It does display 'OK' if the Huanyang VFD is connected and VFD Test has not be saved.

It might be better to get rid of VFD Test, and just include it with 'Custom Modbus'. Another alternative might be to put it on all of the VFD pages allowing users to play around with their VFD settings from the respective page. We may also want to expand the VFD Test table to allow putting multiple commands since many of the commands take multiple writes. 

It might also be useful to include the status field (OK and Disconnected) on all of the VFD pages. That way the user can immediately see if they have the configuration right.

**Comment by jcoffland** [comment]
Fixed in beta 0.3.26.
