### ISSUE TITLE
spindle starts on configuration change

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#157]
The following sequence of events causes my huanyang spindle to start turning:

- Start the spindle running either by running a program that uses the spindle, or by issuing g-code commands (e.g. M3 S5000)

- Click the stop button. This causes the spindle to stop. Do not issue an M5 command to stop the spindle.

- Go to a configuration page, make a change and click "Save". For instance, change the maximum velocity on a motor.

When "Save" is clicked, the spindle starts turning every time.

**Comment by jcoffland** [comment]
Should be fixed now in the latest beta.
