### ISSUE TITLE
Network problems on slow networks with camera plugged in

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#162]
I have been experiencing network problems for that past couple of weeks. I've noticed that sometimes the browser interface seems sluggish and sometimes it disconnects and then reconnects later. I have assumed these were issues with my own network, but now I think there is more to it than that.

Here is a brief description of what is going on now. Whenever, I run 0.3.29 or later software and connect via a browser, the network gets slow and unreliable. Read on to find out why I think this.

With 0.4.1beta loaded, After letting the controller and computer run overnight, I noticed that the browser was not communicating with the controller, but the browser page was open and looked normal. After playing around with it, the browser page said "Disconnected" and then I could not reconnect.

Then I started pinging the controller and found that ping times were ranging up to 3500ms with many packets being dropped altogether.

I restarted the browser, but that didn't help. Next, I rebooted the controller. After that, I was able to connect and ping times dropped to between 50 and 300ms with occasional dropped packets. That still seemed really bad, but at least I could access and control the browser.

Next, I "Upgraded" back to 0.3.28. After doing that, I found that my ping times dropped to between 4 and 11ms, with no dropped packets. Then, I switched from my normal wireless connection to a hardwired connection and the ping times averaged about 1ms.

Next, I tried 0.3.29beta and the ping times went back up, ranging from 70 to 500ms with dropped packets once again.

I "Uploaded" 0.4.1 one again and the long ping times and dropped packets persisted.

I suspected that the long pings and dropped packets were related to real time issues in the raspberry PI caused by the cut path display or the timing feature so I deleted all programs. When I did this, the cut path display just sits there saying "Loading...", and the dropped and slow ping packets persisted. Next, I loaded a short program (729 lines) with just  few lines in it thinking this would not take too much cpu time. The dropped and slow pings persisted.

Finally, I closed the browser altogether, and let the pings continue. The slow and dropped pings continued for several seconds, but then the ping times reduced to 1ms with no drops. I think it takes the Buildbotics Controller a few seconds to determine that the browser connection is gone.

**Comment by jcoffland** [comment]
Do you have the camera connected?

**Comment by DougCoffland** [comment]
Yes, I did have a camera connected. When I disconnect the camera the pinging immediately corrects itself and averages 1ms with no dropped packets.

**Comment by jcoffland** [comment]
I believe the difference is that the camera does not work correctly in 0.3.28.  It sounds to me like your network has routing problems but perhaps we should automatically throttle the camera when the network is slow.

**Comment by DougCoffland** [comment]
I don't have the problem when running 0.3.28. What makes you think my
network is slow?

**Comment by jcoffland** [comment]
But the camera does not work correctly in 0.3.28.  Your ping times are really bad for a local network.

**Comment by DougCoffland** [comment]
1ms is bad?

**Comment by jcoffland** [comment]
300ms is bad.  The Buildbotics controller transmits 640x480 pixel 8-bit color JPEG frames at 12/sec.  Given a modest JPEG compression ratio of 10:1 we can expect that to work out to about ``640 * 480 * 8  / 10 * 12 ~= 3MiB/sec``.  The slowest possible wired network you could have is 10MiB.  More likely you have 100MiB or 1GiB network.

I tested my compression ratio assumption by downloading and extracting one frame.  It was 24k bytes which implies a 15:1 compression ratio and ~2MiB/sec.

**Comment by DougCoffland** [comment]
I got my network problems resolved and now I see about 4ms ping times with the video running. The problem was that I was relying on a wifi dongle on my desktop computer.

I agree with your assessment that we should throttle the video on low networks, so I'll leave this issue open.

**Comment by DougCoffland** [comment]
Resolved
