### ISSUE TITLE
Safari can not open "All file types"

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#163]
One customer is not able to open files that do not have a .ngc extention from his Safari browser on his mac. The problem seems to be that not "Select All File Types" button does not appear in the browser so he cannot open anything with extensions other than ".ngc".

**Comment by jcoffland** [comment]
It currently accepts files with the following extensions: ``.nc``, ``.gcode``, ``.gc``, ``.ngc``.  Other possible file extensions that could be added are ``.txt``, ``.tap`` or , ``.cnc``.  [Here's a list of even more](https://bobcadsupport.com/helpdesk/index.php?/Knowledgebase/Article/View/13/5/known-g-code-file-extensions).  Renaming the file is also an option.

**Comment by jcoffland** [comment]
I'm closing this because other than adding the extra file extensions and allowing any text files, there are no other reasonable changes that would not negatively impact other browsers.
