### ISSUE TITLE
"All zero s-curve times" error

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#167]
The attached code fails to complete and put out an error message that says "All zero s-curve times" .  The same program appears to work fine in CAMotics. I am testing with version 0.3.28 which is the same code that the customer that reported the problem is using.

Also, the same code fails on the G4 P0 statement in 0.4.2-beta, so I can't tell if this is still a problem in 0.4.2.

[new-test_0005.zip](https://github.com/buildbotics/bbctrl-firmware/files/2612734/new-test_0005.zip)

**Comment by jcoffland** [comment]
This is an old bug that has been fixed.

**Comment by DougCoffland** [comment]
I tested the latest version of 0.4.2-beta and it fails now gets past the G4 P0 statement but fails (stopping on line 57) with the same message...("all zero s-curve times"). Apparently, the problem has returned.

**Comment by DougCoffland** [comment]
Wait!. I did not have the new code loaded and was running on 0.3.28. The new code fails with an error message that says "M18: Invalid or unsupported code" and stops on line 9 which is a "G4 P0". Our cheat sheet says that is a dwell command and that it is supported. Since I cannot get past the dwell command, I can't tell whether the problem is fixed.

**Comment by DougCoffland** [comment]
The "All zero s-curve times" error appears to be fixed in 0.4.2, so I am closing this issue and opening an new issue called "Motor move not prepped" to address the inability of the controller to run the new-test_0005 program.
