### ISSUE TITLE
E-stop does not turn off the load switches

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#170]
While testing a new unit with version 0.3.28 software, I noticed that pressing the e-stop button does not turn off the load switches. This is a problem, because the M9 command from the MDI interface does not take affect while e-stop is pressed. The load switch does turn off when the e-stop switch is cleared.

**Comment by jcoffland** [comment]
Fixed in the latest 0.4.2 beta.
