### ISSUE TITLE
Motor move not prepped

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#171]
The attached program e-stops with a message that says "Motor move not prepped". This failure does not occur on V0.3.28 but happens every time on V0.4.2-beta.

The message log says:

warning | Comm | src/command.c:208 | 39 | Machine alarmed - Command not processed

[new-test_0005_no_m18.zip](https://github.com/buildbotics/bbctrl-firmware/files/2621680/new-test_0005_no_m18.zip)

**Comment by jcoffland** [comment]
Fixed in latest 0.4.2 beta.  The problem was in handling zero-length dwells correctly.  I'm not sure what the intention is for such a command.  It should be basically a no-op.
