### ISSUE TITLE
Removed g-code program still on drop-down and 3d simulation

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#174]
When I delete a g-code from the controller, I get the following:
* The program name remains as the selected program.
* The 3D display of the deleted program remains on the screen.
* If I select the deleted program and try to run it, I get an error saying that the program does not exist.
* The program remains on the drop-down list until the controller is rebooted

It would be better if the program was removed from the "selected" field and from the drop-down list, and the 3D display for that program was removed from the display. The way it is now, the user gets no feed back that the program was deleted. This is confusing to the user.

**Comment by DougCoffland** [comment]
After rebooting, I am unable to add any programs to the list. I get a screen that looks like this when I try to add a file.
![screenshot_2018-12-04_08-58-37](https://user-images.githubusercontent.com/8541531/49459023-eabfc880-f7a2-11e8-8cf9-45ced1c259be.png)

I am running 0.4.3-rc1. Deleting g-code files on 0.4.3-rc0 appears to work correctly.

**Comment by jcoffland** [comment]
Should be fixed in 0.4.3-rc2.
