### ISSUE TITLE
spindle stays on after program completes

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#175]
I'm running 0.4.3-rc4. The spindle continues to run after a program is completed. The attached program and configuration can be used to recreate the problem. I don't think this problem started with the current release.

The program ends with M2. According to the LinuxCNC docs, M2 should stop the spindle.

[spindle_doesnt_stop.zip](https://github.com/buildbotics/bbctrl-firmware/files/2647171/spindle_doesnt_stop.zip)

**Comment by DougCoffland** [comment]
I tried the same thing with the Huanyang spindle and it turns off correctly. This problem seems to be limited to the PWM spindle.

**Comment by jcoffland** [comment]
I'm unable to reproduce this in 0.4.3-rc5.
