### ISSUE TITLE
Pause fails

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#177]
Hitting "Pause" and then start results in an error message that says:

error | Planner | Planner.py:326 | 1 | Planner ID 5082 not found.  Next ID is 65966
-- | -- | -- | -- | --

After this error occurs, the program restarts from the beginning. This only seems to happen when running a large program. To recreate the error, let the program run for awhile (perhaps 15 minutes) and then click pause. Then click the start button. The error appears immediately after clicking the start button. The bug report and program are in the attached zip file.

I am running 0.4.3-rc4 using a Chrome browser. Mike Rabin originally reported this problem.

[bug_report_and_program.zip](https://github.com/buildbotics/bbctrl-firmware/files/2658609/bug_report_and_program.zip)

**Comment by jcoffland** [comment]
Fixed in 0.4.3-rc8
