### ISSUE TITLE
User programmable function buttons

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#190]
Randy Savall suggested that we provide some user programmable buttons. These buttons would allow the user to put in a g-code script which would be executed when the button is clicked. Basically, these would be an extension to the MDI interface.

We may also want to make them available when the machine is paused either for a tool change or by a user pause.

**Comment by DougCoffland** [comment]
A second customer has asked for this capability. He said this: "keyboard shortcuts. Not only will they save time but for anyone using a PC, this will allow them to use a keyboard emulator with a gamepad to activate these shortcuts with pad buttons."

**Comment by jcoffland** [comment]
Sounds like two different features.

M-Codes 100-199 are reserved for user defined functions on Linux CNC but are not mentioned in RS274NGC.  I have plans to allow defining them under Settings -> GCode.  These could be mapped to buttons.

**Comment by jcoffland** [comment]
See #204.

**Comment by leadgtr7** [comment]
I'd love to have this implemented. It would be awesome to build a set of buttons using a keyboard emulator for my most used commands like home or probe or zero the coordinates etc

**Comment by tmadrms** [comment]
Please! Would love to automate more. As you keep adding features this becomes even more useful. Keep up the great work!

**Comment by DougCoffland** [comment]
This capability was added in V1.0.0
