### ISSUE TITLE
Add touchscreen virtual keyboard

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#200]
This Chrome extension is an option: https://chrome.google.com/webstore/detail/touch-kiosk-keyboard/lfaiipcbbikbnfcgcmaldlacamgekmnb?hl=en

**Comment by DougCoffland** [comment]
I have been adding xontab virtual keyboard to new units before shipping them for several months. No complaints. I use it on my personal machine with no real issues either.

**Comment by kwince** [comment]
It would be nice to enter a numeric  value relative a printed (msg, menu) and affect operation
are there any flavors of this kind of machine that text user input and checks its value

Sent from AT&T Yahoo Mail on Android 
 
  On Tue, Jan 7, 2020 at 3:28 PM, DougCoffland<notifications@github.com> wrote:   
I have been adding xontab virtual keyboard to new units before shipping them for several months. No complaints. I use it on my personal machine with no real issues either.

**Comment by DougCoffland** [comment]
OS level virtual keyboard added in V1.0.0
