### ISSUE TITLE
Motor 3 is enabled after configuration reset

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#207]
After resetting the configuration from a configuration where Motor 3 was used as a slave to the Y axis, motor 3 remains enabled as the A axis.

I think it should be disabled because most people do not use an A axis.

**Comment by jcoffland** [comment]
This is how it's supposed to work.  We discussed this and decided to enable the A axis by default.  There is little downside to leaving it enabled.
