### ISSUE TITLE
Optimizing out sections of gcode

### ISSUE THREAD

**Issue by RJSavell** [buildbotics/bbctrl-firmware#237]
it appear as if the planner is missing or optimizing parts of the gcode in 0.4.12rc18 (I realize this is beta so perhaps you are already aware but in case you were not I wanted to let you know.

I isolated the section of code to the smallest possible size:

G0 Z15.0
G0 X-2.7961 Y-36.9351
G0 Z1.0
G1 F300.0 Z-0.55
G1 F600.0 X-3.9631 Y-36.9327
G1 X-2.7961 Y-36.9351
G1 X-2.8089 Y-43.0581
G1 X-2.7961 Y-36.9351
G1 F300.0 Z-1.1
G1 F600.0 X-3.9631 Y-36.9327
G1 X-2.7961 Y-36.9351
G1 X-2.8089 Y-43.0581
G1 X-2.7961 Y-36.9351
G1 F300.0 Z-1.6
G1 F600.0 X-3.9631 Y-36.9327
G1 X-2.7961 Y-36.9351
G1 X-2.8089 Y-43.0581
G1 X-2.7961 Y-36.9351
G0 Z15.0
G0 X-7.6912 Y-38.2092
G0 Z1.0

It is a number 1 

CamOptics shows the path correctly:

![image](https://user-images.githubusercontent.com/47092573/71772324-d2bafb00-2f06-11ea-9e79-75ac61e113a2.png)

while the Buildbotics controller only shows and engraves the top of the 1:

![image](https://user-images.githubusercontent.com/47092573/71772335-f5e5aa80-2f06-11ea-9df3-7dc3fcd7873a.png)

Please let me know if you have any questions or need additional details.

Thanks,

Randy

**Comment by jcoffland** [comment]
I found the problem.  It is fixed in [0.4.12-rc19](https://buildbotics.com/bbctrl/bbctrl-0.4.12-rc19.tar.bz2).

**Comment by RJSavell** [comment]
thank you!
