### ISSUE TITLE
Manual firmware upload not working on MacOS

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#245]
Reported in #242.  Files are greyed out.

**Comment by tmadrms** [comment]
Unable to upload firmware via any browser on MacOS -- firmware files are greyed out. 
<img width="828" alt="Screen Shot 2020-02-08 at 3 35 35 PM" src="https://user-images.githubusercontent.com/9586057/74093607-161a0380-4a89-11ea-8dbc-ebf59d15a32d.png">

**Comment by jcoffland** [comment]
This is caused by a long standing OSX bug.  See https://bugs.chromium.org/p/chromium/issues/detail?id=521781 & https://bugzilla.mozilla.org/show_bug.cgi?id=1195508

Work around is to accept all ``.bz2`` files not just ``.tar.bz2``.

Should be fixed in [v0.4.13-rc20](https://buildbotics.com/bbctrl/bbctrl-0.4.13-rc20.tar.bz2).

**Comment by tmadrms** [comment]
Confirmed working in v0.4.13-rc20.  Thanks!!

**Comment by jcoffland** [comment]
Thank you for the report and confirmation.
