### ISSUE TITLE
Completely replace the front-end with other established technologies?

### ISSUE THREAD

**Issue by wulph111** [buildbotics/bbctrl-firmware#253]
What would it take for developers to interface with the motion control back-end from other architectures? For example, bCNC or a USB Motion Plugin for Mach3 controlling the BuildBotics controller instead of the standard web-based GUI? 

These systems have unique features that would help users transition to BuildBotics more seamlessly. I am interested on working on this feature, but I'm not familiar with the codebase so some guidance would be welcome.

**Comment by jcoffland** [comment]
There's not practical way to do this.
