### ISSUE TITLE
Add Ability To probe with a button or macro without a gcode file loaded

### ISSUE THREAD

**Issue by myerswoodshop** [buildbotics/bbctrl-firmware#261]
Shapeoko and xcarve do this, able to probe and set xy or z without a gcode file loaded.

**Comment by leadgtr7** [comment]
@jcoffland @DougCoffland  any idea when macros will get implemented? I think that it will be a great edition and allow user to customize their machines much easier. I'll be glad to be a guinea pig

**Comment by DougCoffland** [comment]
resolved with macro buttons in V1.0.0
