### ISSUE TITLE
Motors go idle during a program/carve

### ISSUE THREAD

**Issue by dacarley** [buildbotics/bbctrl-firmware#288]
We've hit an issue with the OneFinity flavor of the BuildBotics controller.  We've had a few carves that were unable to maintain straight lines when moving along strictly one axis.

With a little "air carving" and empirical testing, I was able to determine that the motors go "idle" even a gcode program is being run.

If leave the idle current at the default of 0.5, I can easily move the X carriage in the Y direction when the gcode is moving exclusively in the X direction.

If I boost the idle current up to the maximum of 2.0, and perform the same test, I cannot move the carriage in the Y direction manually.

This seems like a major flaw.  Why is any motor ever considered "idle" during a gcode program?

**Comment by jcoffland** [comment]
We cannot help with OneFinity problems.  Sorry.
