### ISSUE TITLE
LinuxCNC-on-RPi

### ISSUE THREAD

**Issue by r13doc** [buildbotics/bbctrl-firmware#289]
Does you controller work without wi-fi connection? 
Can I use ruspberry pi with a touchscreen function on  linuxCNC   with Buildbotics Controller ??

**Comment by jcoffland** [comment]
The Buildbotics controller can be accessed with wifi or wired ethernet.  you can also connect a touch screen or mouse, keyboard and monitor directly to the controller.  LinuxCNC is not needed.  You can use [CAMotics](https://camotics.org/) to simulate your GCode and send it to the Buildbotics controller.

**Comment by kwince** [comment]
No. I have the controller hooked up to an ethernet cable, but I use my
phone on wifi to on the LOCAL NETWORK ONLY (cellular data off) to connect
to the controller.

**Comment by r13doc** [comment]
Thanks, tell me please can I use this controller locally, for example
through camotics installed on my deb-ruspberry pi , without wifi or
ethernet ?
I am from Russia there is a problem with Ethernet and wi-fi...
Can I use for example nema 23 57HS76-3004 with this controller?

**Comment by jcoffland** [comment]
You can use it with out Wifi or Ethernet if you put the GCode on an SDCard.   CAMotics will not run on the RPi.  You can use petty much any nema 23 motor as long as it's not uni-polar.  The one you listed will work.

**Comment by r13doc** [comment]
Cool, thanks! You are the best!!

**Comment by kwince** [comment]
Denis,
Gdyeh v'Russiya ti  zhivyosh?
