### ISSUE TITLE
3D view not working on Chrome

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#291]
The 3D View does not display on Chrome. I tried if from my Debian desktop with Chrome version 74.0.3729.108 and from a Mac laptop with Chrome version 89.0.4389.82.

It works with Firefox

**Comment by jcoffland** [comment]
It works in Chrome for me. Chrome version 85.0.4183.102.  I doubt it's a Chrome issue.  Your browsers probably lack WebGL support.  Visit this site to check: https://get.webgl.org/

**Comment by DougCoffland** [comment]
I went to that web site. It displays a rotating cube which suggests that I have webgl installed.

**Comment by jcoffland** [comment]
What do you see at this page?:  https://webglreport.com/

**Comment by DougCoffland** [comment]
It says "✓ This browser supports WebGL 1" at the top of the page.

**Comment by DougCoffland** [comment]
It also says "✓ This browser supports WebGL 2" at the top of the second tab.

**Comment by DougCoffland** [comment]
Fixed in 1.0 rc7. May require clearing cookies.
