### ISSUE TITLE
Homing after Stop causes error and leaves machine in 'HOMING' state

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#294]
The following sequence of events causes an error:

1. Home the machine
2. Start a program.
3. Stop the program before it completes. Machine state returns to 'READY'.
4. Click 'Home' button.

The error looks like this:

Level | Source | Location | Repeat | Message
-- | -- | -- | -- | --
error | Planner | Planner.py:421 | 1 | Z axis position 766.451mm is greater than maximum soft limit 200mm While executing GCode block:G38.6 Z[#<_z_home_travel>]        At: <MDI>:3 Caused by: Z axis position 766.451mm is greater than maximum soft limit 200mm
error | Planner | Planner.py:421 | 1 | Z axis position 618.297mm is greater than maximum soft limit 200mm While executing GCode block:G38.6 Z[#<_z_home_travel>]        At: <MDI>:3 Caused by: Z axis position 618.297mm is greater than maximum soft limit 200mm
message | Planner | EMTEC/buildbotics.gc:11 | 1 | Remove probe
message | Planner | EMTEC/buildbotics.gc:4 | 1 | Change tool and attach probe

You can acknowledge the error, but the state on the user interface remains in 'HOMING'. Clicking 'Stop' or 'Pause' has no effect, and you really can't do anything.

The only ways out of this condition are to set and clear estop or reboot.

**Comment by jcoffland** [comment]
Is this fixed by bbctrl-1.0.0-rc10.tar.bz2?
