### ISSUE TITLE
Units dropdown is gone on main control page

### ISSUE THREAD

**Issue by leadgtr7** [buildbotics/bbctrl-firmware#295]
Noticed that I can't switch units on the main control page via dropdown anymore in latest rc10

I use the feature alot, I find it easier to set my x0 y0 in metric and write this value down should i need to hit the big red button it makes it easier to get back. I do however run most of my CAM in inches

**Comment by DougCoffland** [comment]
This is by design. You can now add a macro button to change units if so desired.
