### ISSUE TITLE
Custom Steps per Rev

### ISSUE THREAD

**Issue by leadgtr7** [buildbotics/bbctrl-firmware#312]
Now that the new hardware is going to support external stepper drivers is it possible to have a custom steps/rev value?

My external closed loop steppers have a 1000 count/rev encoder as well as a 1000 steps/rev setting and it would be nice to be able to use that.

**Comment by DougCoffland** [comment]
Yes, you can adjust the steps per revolution by adjusting the 'step-angle'
parameter on the motor configuration page.

Doug
