### ISSUE TITLE
Ways to Support Firmware Devolpment

### ISSUE THREAD

**Issue by leadgtr7** [buildbotics/bbctrl-firmware#314]
Hi Joe and Doug,

Have you considered a patreon (or something similar) to help fund development on the controller?

I wouldn't mind kicking in a couple bucks a month if it helped develop new features more quickly

**Comment by jcoffland** [comment]
We need to look into that.  Don't you need to produce regular content to make money on Patreon?

**Comment by leadgtr7** [comment]
I'm really not sure. But if a couple bucks a month could get some of these
feature requests fast tracked I'd chip in

**Comment by cwallen93117** [comment]
Agreed will chip in as well.

**Comment by leadgtr7** [comment]
@jcoffland I don't immediately seeing anything that says there has to be regular content. If that was a requirement I think you could make the case that any firmware updates could qualify
Here's a link to the legal page if it's something you and @DougCoffland want to pursue
[https://www.patreon.com/policy/legal](https://www.patreon.com/policy/legal)

**Comment by jcoffland** [comment]
Ok.  I've done it.  How does it look?  https://www.patreon.com/buildbotics

I'll have to add this to our website too.  Thanks for the suggestion.

**Comment by leadgtr7** [comment]
Well you have your first patron, hope it helps :)

**Comment by cwallen93117** [comment]
Now you have 2

 

Charles Allen

e-mail:  ***@***.***> ***@***.***

**Comment by jcoffland** [comment]
Awesome.  Thanks to both of you.

**Comment by cwallen93117** [comment]
Np.  Also you should put link on your website, next to the facebook, youtube, etc. logos on the top banner.

**Comment by jcoffland** [comment]
Done.
