### ISSUE TITLE
error handling G53 commands i.e. move in machine coordinates

### ISSUE THREAD

**Issue by cwallen93117** [buildbotics/bbctrl-firmware#316]
It appears that when the buildbotics generates both the gcode warnings and 3d view it ignores any G53 Machine position moves, e.g. “G53 G0 Z150 “ and treats them as starting from the work coordinate origin e.g. “G0 Z150”.  See the image from the 3d viewer below.  The work coordinates were set at the blue/green/red origin.  

 
![Screen Shot](https://user-images.githubusercontent.com/42359081/145468572-650032eb-e152-4633-9f86-8591a58ed85c.png)

**Comment by jcoffland** [comment]
Looks like it doesn't take the work coordinates into account.

**Comment by cwallen93117** [comment]
Anyway this can be fixed?Charles917-359-4714Sent from my smartphone
-------- Original message --------From: Joseph Coffland ***@***.***> Date: 12/11/21  3:34 PM  (GMT-05:00) To: buildbotics/bbctrl-firmware ***@***.***> Cc: cwallen93117 ***@***.***>, Author ***@***.***> Subject: Re: [buildbotics/bbctrl-firmware] error handling G53 commands i.e. move in machine coordinates (Issue #316) 
Looks like it doesn't take the work coordinates into account.

**Comment by jcoffland** [comment]
I'll take a look.

**Comment by stromi65** [comment]
look at [https://github.com/buildbotics/bbctrl-firmware/issues/297] - same problem, was not fixed yet

**Comment by DougCoffland** [comment]
fixed in version 1.0.2
