### ISSUE TITLE
Support Fuling Model DZB200 Series VFD

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#321]
![image](https://user-images.githubusercontent.com/1166284/150169099-c167072d-1d31-410a-8e48-5f8abb672550.png)

It is set up on address 1 at 9600 baud, with parity = None.

Here are the register settings in the VFD:

    F0.01 = 2
    F0.03 = 6
    F0.04 = 1000.0
    F6.00 = 1 (matches Buildbotics Address setting)
    F6.01 = 3
    F6.02 = 3

https://salecnc.com/manuals/DZB200&300CC.pdf

**Comment by DougCoffland** [comment]
fixed in version 1.0.2
