### ISSUE TITLE
Can not make the probe work

### ISSUE THREAD

**Issue by makerstorage** [buildbotics/bbctrl-firmware#55]
I connected a wire to pin 22 of the I/O connector. I put a button between gnd and this pin.
I set the probe normally-open from the drop down menu in the I/O section of the web interface.
I opened the indicators section. The probe led is green but not changing when I press the button.
Same setup works with the estop.

**Comment by DougCoffland** [comment]
I have the same problem. The probe indicator does not change when the state of the probe switch changes.

**Comment by jcoffland** [comment]
Fixed in v0.3.5.
