### ISSUE TITLE
Web cam requires controller and browser restarts

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#59]
I tried plugging a web cam to our box.  The browser did not display the video.  I found that I have to reboot the controller and restart (refresh won't do) the browser after plugging in the web cam to get it to work.  This seems cumbersome.

**Comment by jcoffland** [comment]
I have a Logitech C615 webcam and it seems to work fine.  I only need to switch tabs to get it to reload the video feed.

**Comment by DougCoffland** [comment]
I currently have browsers from two different computers connected to the controller. One is able to display the video and the other is not. Switching tabs does not help. Occasionally, I can get the video to display on both.

**Comment by DougCoffland** [comment]
After waiting several minutes, the video appeared on the other browser. Now, it's showing on both.

**Comment by jcoffland** [comment]
Running two streams is probably taxing your network, especially if you're trying to do this over Wifi.  Probably a networking issue that's not our problem.  We should mention this in the documentation though.
