### ISSUE TITLE
Set axis position prompts for a value but doesn't use it

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#60]
The gear shaped button in the axis table on the control page seems to have strange behavior.  After clicking it, the user is prompted to enter a Position value.  The Position value is always set to 0.000, the Absolute value is not affected, and the Offset value is set to the reciprocal of the Absolute value, no matter what value the user enters.  The behavior seems to be the same as clicking the middle button except the middle button does not prompt for a value.

I have tested this in the "manual" homing mode only.  I will try it in the "switch-min" and "switch-max" modes as I get to them.

**Comment by jcoffland** [comment]
Fixed in v0.3.5.
