### ISSUE TITLE
Large G-Code program hangs browser on deletion

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#64]
I loaded a large G-Code program into the browser.  It took quite a few seconds to load the file, but it took.  The program is about 75,000 lines long.  When I delete the program, it hangs the browser.  After selecting "Wait" in the dialog that says the browser is not responding a few times, the browser eventually comes back and everything is OK.  User's are likely to get frustrated waiting so long for files to be deleted.

**Comment by jcoffland** [comment]
Fixed in v0.3.5.

**Comment by jcoffland** [comment]
Fixed in v0.3.5.
