### ISSUE TITLE
Load switches not working

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#70]
The load switches do not respond to M7, M8, or M9 commands.

**Comment by jcoffland** [comment]
Do you have them configured in the Web interface?

**Comment by DougCoffland** [comment]
The only configuration that I have found is on the tool page for load-1and
load-2 and those are both set lo-hi.


On Jan 14, 2018 1:36 PM, "Joseph Coffland" <notifications@github.com> wrote:

Do you have them configured in the Web interface?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/buildbotics/bbctrl-firmware/issues/70#issuecomment-357544495>,
or mute the thread

**Comment by jcoffland** [comment]
Try upgrading your firmware to 0.2.2 and check if they are changing on the ``indicators`` tab of the control Web page.

**Comment by DougCoffland** [comment]
I upgraded to 0.3.1 and the load switches now work.
