### ISSUE TITLE
Spindle does not respond to M3, M4, or M5 commands

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/bbctrl-firmware#72]
I have loaded 0.3.1.

The indicators tab now shows that the correct state for the tool-enable-mode output. However, the output still does not change when M3, M4, or M5 commands are issued.

I am sure that the Dyna wiring is correct because I can cause the spindle to start and stop by changing the tool-enable-mode output on the TOOL configuration page from lo-hi to h-lo.

The RS-485 spindle does not work either.

**Comment by jcoffland** [comment]
I created #73 for the RS-485 issue.
