### ISSUE TITLE
RS-485 spindle not working in 0.3.x firmware

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-firmware#73]
CC @DougCoffland

**Comment by DougCoffland** [comment]
My RS-485 spindle works intermittently. It's possible that there is a hardware problem with my VFD spindle. Joe, you will need to test with your VFD to see if you get the same result.

I noticed that when mine is working, the status indicator for the RS-485 spindle is  constantly changing between "connected" and "not connected"

**Comment by jcoffland** [comment]
It seems to be working.  I've made some additional improvements in 0.3.7.
